In [3]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [29]:
#price = m1*area + m2*bedrooms + m3*age + b
#price = m1x1 + m2x2 + m3x3 + b

In [30]:
df = pd.read_csv('data.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [31]:
df.bedrooms.median()

4.0

In [32]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [33]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price', axis='columns'), df.price)

LinearRegression()

In [34]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [35]:
reg.intercept_

221323.00186540408

In [36]:
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [37]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])